### PR TITLE
Add 2D support to D88 reader.

### PR DESCRIPTION
**Pull request by tdaede**
Add 2D support to D88 reader.

### CODE REVIEW

**Comment by keirf** [comment]
2D format is like a regular DD track but spun at 300rpm rather than 360rpm? So the track gap is *massive*?

**Comment by tdaede** [comment]
For PC88/PC98 it normally goes:

2D = 300rpm, 250khz clock, 40 track
2DD = 360rpm, 250khz clock, 77 track
2HD = 360rpm, 250khz, 77 track

2DD is pretty rare, I haven't found anything written like that yet.

The track gap is not massive as most 2D disks shove more sectors in to compensate.

**Comment by tdaede** [comment]
BTW I'm primarily using the links at the bottom of this page as reference for these formats: https://www.pc98.org/project/fivec.html

**Comment by keirf** [comment]
All merged so far. Would there be a sensible point for a v1.4 release soon?

**Comment by tdaede** [comment]
Yes. I actually just sent a couple people a link to the build artifact for them to test. If they report back success I think it's feature complete enough to use for maybe 90% of images now.

**Comment by keirf** [comment]
Great news. Please suggest a bullet or two for the release notes.

**Comment by tdaede** [comment]
It seems pretty solid so far. I still have things I want to fix of course, but:

- Added read support for DIM, FDI, HDM, XDF, and D88 image formats (primarily used with Japanese computers)
- Renamed pc98.hd and pc98.dd formats to pc98.2hd and pc98.2dd
- Fixed head count on pc98.2hd and pc98.2dd formats
- Added support for pc98.2d format (used e.g. by PC-88 and X1)
- Added support for pc98.2hs format (used primarily by late PC-98)

**Pull request merged**
