### PR TITLE
Add Apple floppy types

### PR DESCRIPTION
**Pull request by jepler**
Hi! For Adafruit, it's my intention to extend the Greasweazle protocol so that it can support Apple II-style floppy drive interfaces. I'm new to Apple II disk reading & preservation so I will have a lot to learn.

Compared to a PC or Shugart interface, there are some notable differences:
 * Instead of step & direction, there are 4 "winding activation" signals. The GW-compatible hardware will generate these outputs on hardware-defined pins.
 * While the track spacing is the same as a PC "double density" disk, the read/write head can be positioned 1/4 as finely as a single track spacing. Apparently, this is used in copy protected Apple II software, similar to fat/half tracks in Commodore 64, just worse.
 * There is no "track 0" sensor, instead the "bang your head into a wall" algorithm is used.
 * There is no index sensor, though we anticipate recommending a reflective IR sensor modification and are OK if it is required
 * The 'write' signal is different than for a PC drive: a flux reversal is written when the write data line is inverted, rather than when it is pulsed.

Consequently, I would like to allocate two new numbers for 'bus type': Apple2 and Apple2QuarterTrack. These would be accessed with `--drive APPLE2` and `--drive APPLE2_QUARTERTRACK` in the GW commandline.

Together with pending changes in fluxengine,

### CODE REVIEW

**Comment by keirf** [comment]
I was wrong on (2): Of course it is hard to only accept supported drive letters at arg parse time as we haven't opened the GW device at that time. We'll just have to come up with an elegant descriptive error message at the time of attempting to set the bus type.

**Comment by keirf** [comment]
(2) is now fixed well enough in master

**Comment by jepler** [comment]
I've updated and revised this PR. Thank you for adding the improved error handling! Adafruit_Floppy does use a BadCommand response for an unsupported bus type, so that is great for us.

Now, the --drive arguments are `--drive APPLE2` and `--drive APPLE2_QUARTERSTEP`, and all sites that take `--drive` have their help updated. The Apple II 20-pin connector only supports a single drive, so at this time there's no need to support `APPLE2:1`. While there is a 19-pin connector that supports a chain of 2 drives, this connector is difficult to obtain, so it's nothing we're interested in doing at this time.

With Adafruit_Floppy's gw-compatible firmware, a hand-wired interface board, and a modified fluxengine (https://github.com/davidgiven/fluxengine/pull/492) it's possible to read and write standard Apple II floppies using a Disk II drive.

I hope you'll consider merging this PR to officially allocate the bus type numbers for Apple 5.25" disks, so that the changes in fluxengine can move forward.

**Comment by keirf** [comment]
The drive id names may change after I pull this. I will intend them to be stable from next Greaseweazle tools release.

**Comment by jepler** [comment]
Thank you!

**Comment by keirf** [comment]
I think we should stick with one Apple2 bus type, this should always quarter step, and if you want half or whole steps this can be done in the Greaseweazle `--tracks` TSPEC option. For example, `--tracks=c=0-39:step=4` will read 40 cylinders with 4 quarter steps between each cylinder. Or `--tracks=c=0-79:step=2` to read 80 half tracks. Etc.

I therefore propose to rename Apple2Quarter to Apple2, and remove the old Apple2 assignment.

**Comment by keirf** [comment]
> @davidgiven can fluxengine do the equivalent? If so this sounds great to me.

fluxengine has fancy config file stuff now that should handle this even better. Probably a couple of different disk types with nice names, which hide the actual ranges and stepping multipliers.

**Comment by davidgiven** [comment]
Yup, that's a good idea --- in fact, I recently added a configuration stanza for drive configuration.

Currently dealing with different disk and drive types is a mess and barely works, and it needs redesigning, so this is as good an opportunity as any. I'll take a look.

**Comment by davidgiven** [comment]
I've done a gigantic FluxEngine refactor to make it less of a mess, and also improve reading and writing where the drive track spacing doesn't match the format track spacing (e.g. a 40-track format on an 80-track drive). This should now, hopefully, support Apple II drives on Greaseweazle. However, I don't have one and so can't test. Can someone try plz?

The code's at: https://github.com/davidgiven/fluxengine/tree/logical

The necessary command is:

`fluxengine write apple2 apple2_drive -i someimage.img -d drive:0`

The `apple2_drive` profile contains the settings for the drive, which I believe to be 192 tpi, 160 tracks, with a head width of 4.

**Pull request merged**
