### PR TITLE
Only use setuptools for the build system.

### PR DESCRIPTION
**Pull request by ieure**
This replaces the existing build system with setuptools, and reorganizes the source tree.  I did this because I was interested in packaging the tools for Debian, but the current build system makes it impossible.

Currently, the build consists of:

- `make(1)`, via `Makefile` and `Rules.mk`.  These hold the project version and geneate Python code to hold it, and create source distribution tarballs.
- `scripts/setup.py`.  Uses cx-Freeze to create an executable.
- `scripts/c_ext/setup.py`.  Uses distsutils (which is deprecated), but for the `optimised` C extension only, which is a separate Python package from the rest of the code.
- `scripts/setup.sh`.  Ad-hoc tooling which installs dependencies and the c_ext package into the Python code source tree.

The complexity and inter-dependence of this system makes it very difficult to use, maintain, and package.

This change:

- Merges the c_ext and Greaseweazle packages into a single one (`greaseweazle`).
- Creates a single, top-level `setup.py` for both the Python and C code.
- Uses setuptools’ `entry_points` for the `gw` executable, rather than cx-Freeze or the ad-hoc `/gw` wrapper script.
- Removes all `make(1)` and distutils usage.
- Reorganizes the code on disk:
  - Inside `scripts/`, `greaseweazle`, `c_ext`, and `misc` have moved to the root of the repo.  This is where setuptools expects the Python and C code to be.
  - `scripts/gw.py` moved to `greaseweazle/cli.py`.
  - `scripts` removed, since it no longer contains anything.
- Reworks `greaseweazle/cli.py`:
  - Checking of imports has been removed.  Dependencies are declared in `setup.py`, which means a proper installation will always have them, so it’s no longer necessary.
  - Code in the package itself has been moved into a `main()` function.
- Changes versioning.
  - `greaseweazle.version` now uses `pkg_resources` to introspect the version out of `setup.py`, which is the source of truth for it.
  - Checking for `greaseweazle.version.commit` has been removed, since it never exists now.

I understand this is a large change, but I believe that it -- or something close to it -- is necessary for greaseweazle to be a well-behaved Pythonic package.

### CODE REVIEW

**Comment by ieure** [comment]
There are a couple aspects of this which may need additional care:

- Creation of dist tarballs.  This can be accomplished with `python setup.py sdist`, though it likely needs some tuning.  Or, GitHub can create release tarballs from Git tags.
- Installation is now done via `python setup.py install`, or producing a dist via `python setup.py bdist` and installing the egg.
- `misc/` script handling.  It may be nice to move these into the main source tree and add `entry_points` for them.
- Removing cx-Freeze likely means that standalone Windows binaries aren't produced.  I don't run Windows, but would be willing to iterate on this.

**Comment by keirf** [comment]
I have no problems with some big changes to the build system here. As you say, it's all Python but with some horrible Makefile kludge on top. But the github workflows need to still work, and that means at least Windows executables. If a download tarball of the repo itself can count as a release for everything else, that could be okay.

I don't know if you're familiar with GitHub CI, but there is a build file in `.github/workflows/ci.yml` and you get nice build logs.

The stuff under `misc/` doesn't matter too much.

But at the end of the day 90% of users or more are on Windows and use the binary dist, so the tail can't wag the dog even if the dog is one ugly mutt. We'll have to iterate on that and work out how to incorporate cx_Freeze.

**Comment by keirf** [comment]
However I do like the approach of course, and it would be great to have the project included in Debian and its downstream distros. I will have a look at fixing up cx_Freeze and getting the CI workflow running on top of your work. I expect you've done the heavy lifting really and I'll just be making it jankier again!

**Comment by keirf** [comment]
Ok I took a look and I can build on this no problem. I will expect that distros will take a release source tarball and make packages from that, rather than taking the source repository directly. Is that reasonable?

**Comment by ieure** [comment]
Thanks for the quick reply.


> I don't know if you're familiar with GitHub CI, but there is a build file in `.github/workflows/ci.yml` and you get nice build logs.

I've used them before, but haven't built any.  I don't anticipate any great difficulty in fixing them up, and anticipated that they'd be broken, but I couldn't see what was broken.  CI runs don't work for first-time contributors, I assume because they were being abused.

> But at the end of the day 90% of users or more are on Windows and use the binary dist, so the tail can't wag the dog even if the dog is one ugly mutt. We'll have to iterate on that and work out how to incorporate cx_Freeze.

Makes sense, thank you for the context.  Since that stuff is only needed for producing the binary releases, I think the simplest thing is to add the original `setup.py` back, but under a different name, like `binary.py` or `setup-cx.py` or something like that -- then update the CI workflow to use it.

> However I do like the approach of course, and it would be great to have the project included in Debian and its downstream distros.

Just to set expectations here, I'm no longer a Debian developer and have no power to include gw in Debian.  But it can be used to provide unofficial packages, and/or as a base should a Debian developer want to include it.

> I will have a look at fixing up cx_Freeze and getting the CI workflow running on top of your work. I expect you've done the heavy lifting really and I'll just be making it jankier again!

Sounds good.  I'm happy to pitch in here as well, if you need or want me to.

>  I will expect that distros will take a release source tarball and make packages from that, rather than taking the source repository directly. Is that reasonable?

Either approach works & they're both valid; it varies by project and developer preference.  My understanding (and preference) is that for projects which natively use Git, you should leverage that.  You clone the repo and create an `upstream` branch and `upstream/VERSION` tag for the upstream release, and `main` (or `master`) becomes the branch with the Debian packaging added to it.  When a new upstream release occurs, you fast-forward `upstream`, create a new tag, and merge into `main`.

So, once that's possible, I can fork gw and push my commits that add the Debian packaging there.

**Comment by keirf** [comment]
> Just to set expectations here, I'm no longer a Debian developer and have no power to include gw in Debian. But it can be used to provide unofficial packages, and/or as a base should a Debian developer want to include it.

Ah that's a shame. Still, I'm sure the state that the build/packaging system is in right now would dissuade most potential distro developers.

> > I will expect that distros will take a release source tarball and make packages from that, rather than taking the source repository directly. Is that reasonable?
> 
> Either approach works & they're both valid; it varies by project and developer preference. My understanding (and preference) is that for projects which natively use Git, you should leverage that. You clone the repo and create an `upstream` branch and `upstream/VERSION` tag for the upstream release, and `main` (or `master`) becomes the branch with the Debian packaging added to it. When a new upstream release occurs, you fast-forward `upstream`, create a new tag, and merge into `main`.
> 
> So, once that's possible, I can fork gw and push my commits that add the Debian packaging there.

Ok that makes sense. Actually I think my tarball would likely be either exactly the repo, or the repo minus files I don't want/need to distribute in a release. So I expect either will work.

**Comment by ieure** [comment]
I poked at the workflows a bit, but I don't have a single Windows box to test stuff on, so I'm not sure what all needs to happen there.

My recommendation would be, roughly:

 - Rename the `ci` workflow to `snapshot` and have it trigger on commits to `master`.  Typically, a CI workflow would perform some automated checks to determine the suitability of a PR branch for merge, ex. run tests, make sure code matches project style, etc.  I'm honestly not sure what utility snapshot releases have for GW -- in my experience, they're generally not very useful -- but you definitely don't want them triggering on PR branches, only changes to the default branch.
 - Fix up the Windows `release` workflow.  Might be easiest to define the steps in the action, but you could put them in a script or `Makefile.windows` or something like that.
- If you decide to add unit tests, pip8 linting, etc, put those in a new `ci` workflow.

**Comment by keirf** [comment]
I'll have a sift through your bits when I have some time. I have enough to be getting on with now. Probably I'll still have a top-level Makefile but really just as a glorified script dispatcher. `make install`, `make uninstall` and the like, mapping to things like `python3 -m pip install --local setup.py`. Perhaps for snapshot releases I'll make an sdist. I'm undecided.

Regarding copyright, I see a copyright message in the new version.py file. But currently the whole project is unlicense (PD). I am thinking though to move to a relaxed license+copyright such as MIT or BSD, as this seems more acceptable generally than full Public Domain. In which case I may simply "Copyright 2022 The Greaseweazle Authors" in the top-level COPYING or LICENSE file, plus the license. And update all source files accordingly. Is that agreeable?

**Comment by ieure** [comment]
> I'll have a sift through your bits when I have some time. I have enough to be getting on with now. Probably I'll still have a top-level Makefile but really just as a glorified script dispatcher. `make install`, `make uninstall` and the like, mapping to things like `python3 -m pip install --local setup.py`. Perhaps for snapshot releases I'll make an sdist. I'm undecided.

This seems reasonable to me.

> Regarding copyright, I see a copyright message in the new version.py file. But currently the whole project is unlicense (PD). I am thinking though to move to a relaxed license+copyright such as MIT or BSD, as this seems more acceptable generally than full Public Domain. In which case I may simply "Copyright 2022 The Greaseweazle Authors" in the top-level COPYING or LICENSE file, plus the license. And update all source files accordingly. Is that agreeable?

Ah, sorry, this is my standard blank file template; I'll remove it.  As long as the license is nominally FOSS (permitting redistribution and reuse), I don't have a strong opinion on the specifics, and am happy to go along with whatever you think best reflects the needs & goals of the project.

**Comment by keirf** [comment]
I have manually reworked and merged this PR. Both workflows tested working. Thanks for the inspiration!

**Comment by ieure** [comment]
That's great news, thank you!  This was a high-quality interaction that went a lot better than I was afraid of.

**Pull request closed without merging**
