### PR TITLE
`gw info`: Add rate limit check for GitHub API

### PR DESCRIPTION
**Pull request by yzqzss**

### CODE REVIEW

**Comment by keirf** [comment]
Thanks. Do we know what the rate limit is and have we seen it exceeded? Might there be a similar concern for downloads during gw update? And, finally, do you know if there's a way to increase these limits if they become a problem?

**Comment by keirf** [comment]
Ah maybe this is the 60 requests per hour anonymous limit.

Download of firmware would be probably subject to 5000/hr limit which is rather harder to hit.

I'll have a play. I'm sure I can trigger the limit.

**Comment by yzqzss** [comment]
> Ah maybe this is the 60 requests per hour anonymous limit.

Yeah, when I repeatedly `gw info` to check the F1 board I made, it triggered the rate-limit. So <https://github.com/keirf/greaseweazle/blob/e7c655ca14bf32b1c342cc05da11f3b2c3566e5d/src/greaseweazle/tools/info.py#L50> gave me a simple `KeyError` message. This made me think "is there something wrong with my F1 board?" lol.

> Might there be a similar concern for downloads during gw update?

Yes.

> if there's a way to increase these limits if they become a problem?

I don't know, but it shouldn't be difficult for people to just wait a little while to cool-down the limit or open github.com to manually download the firmware update?

**Comment by keirf** [comment]
Extended and applied to master.

**Pull request closed without merging**
