### PR TITLE
Add stepper motor exercise function

### PR DESCRIPTION
**Pull request by ali1234**
Steps the head to ecyl and then back to scyl repeat times.

Implements #32

### CODE REVIEW

**Comment by dwillmore** [comment]
Can you add a check that the TRACK0 signal is asserted when expected?  That's a good way to detect missed steps.  If it comes too early you lost steps going out.  If its asserted too late, you lost steps coming back.  Either way, that's a useful diagnostic.

Might also want to put an option to pause--to give the operator a chance to lubricate or clean the drive assembly.  If keyboard interaction is possible, maybe have a "press ENTER to seek to <target_cyl".  You'd want it going both directions.  Thanks for your work on this!

**Comment by ali1234** [comment]
It doesn't seem like it is possible to detect early/late TRACK0. Stepping to 0 is a special case and the firmware will always try to step down 256 times, or until TRACK0 is asserted. It only returns an error if TRACK0 is never asserted, not if it is early or late.

**Comment by dwillmore** [comment]
I guess it's going to need a firmware modification, then. :(  Thank you so much for all of your work today!

**Comment by keirf** [comment]
I'm going to have to think about this. Perhaps as a stepper-exercise command this can make sense, with whatever bells and whistles. It's a bit more than makes sense as 'gw.py step' isn't it.

**Comment by keirf** [comment]
I'm not sure the --scyl --ecyl syntax is a good fit here either. Do you ever want --scyl other than zero? If not I'd nuke --scyl, and change --ecyl to simply be a numeric positional parameter.

**Comment by ali1234** [comment]
Agreed, see commit message.

**Comment by ali1234** [comment]
I think there is something to be said for consistent argument spec across modules though.

**Comment by dwillmore** [comment]
I can see wanting --scyl if we had a way to check head position by reading sector headers.  Otherwise, only Track 0 makes any sense for it.

**Comment by keirf** [comment]
I believe that this exercise functionality is well covered by scripted calls to `gw seek`, or use of `gw clean`.

**Pull request closed without merging**
