### PR TITLE
add generic Adafruit_Floppy example

### PR DESCRIPTION
**Pull request by ladyada**
re-opening of https://github.com/keirf/greaseweazle/pull/140 without the debugging stuff! (github autoclosed the last one when switching out branches)
requested changes will be made in this PR

### CODE REVIEW

**Comment by ladyada** [comment]
> Thanks for these patches! I will have a number of comments, and also I need to formulate a position on third party firmwares, a situation which simply hasn't arisen in the past!
> 
> I suppose the first question is: How do you propose to package and sell these (kits, assembled, DIY project for the adafruit blog, ...). Will it be a "Greaseweazle", or a different name (I'm ambivalent on this by the way, in some senses it is a Greaseweazle, in others it's not). I am happy to discuss any of that here, in PR or issues, or by email. Especially if it carries the Greaseweazle name, I'm concerned about quality, particularly accuracy of flux handling in the firmware. Eg. 20MHz precision is okay, but gathering flux in a software loop is potentially inaccurate, for example dropping timer ticks. RP2040 for sure must be able to do better with its PIO, right? (Right? Actually I googled for examples of this rather obvious timer-capture type behaviour and only found aggressive Pi-fanboy responses. So perhaps it can be done, or perhaps not, or perhaps yes but it's very hard).
> 
> Regarding these specific tools patches, some initial feedback:
> 
>     The debugging changes belong in a separate PR, or at least in a completely separate patch. I don't know if I want them as is and they get in the way of the other functional changes.
>     Changes to score_port(): A brand new firmware should be able to advertise solely on manufacturer/product/serial strings. The VID/PID stuff is for supporting really old Greaseweazle bootloaders. I'd rather not trigger on everything in the Pi and Adafruit universes.
>     Actually at the end of the day, a slight tweak to score_port() and to the product name list in info.py is probably what this all boils down to. Perhaps also rejecting (or differently handling) these devices in update.py also. So this PR ought to be pretty tiny!
> 
> The conclusion is: Yes, in principle. It mostly depends on acceptance of a new brand or Greaseweazle submodel into the project, which is more a mix of non-technical and firmware-technical questions than any problem with the required trivial tools patches.

> Here's an example that would be readily acceptable to me (specific names and strings here are just examples!):
> 
> "Adafruit Floppy Interface [....] supported by Greaseweazle tools."
> 
> Device USB strings:
> Manufacturer: "Adafruit"
> Product: "Floppy Interface"
> Serial: Up to you, could be existing GWxxxxxx format, or your own, or none at all. But a serial based off an MCU serial is a nice to have.
> 
> This avoids any confusion with Greaseweazle devices of my own design with firmware under my control.

**Comment by ladyada** [comment]
OK here are some answers!

1. we would not call any hardware or project "GreaseWeazle" - that's your hardware / project.  the hardware we do, will be called something like "Adafruit Floppy Feather" or "Adafruit Floppy Friend" or something similar (let me know any feedback on that as needed too). we would use greaseweazle as one of the softwares to use to transfer data from the actual diskettes. the hardware will likely support both 34pin IDC, 26 pin FPC, and 20p disk ][ hardware, ideally the PCB will be 💾 shaped ;)
2. regarding accuracy, yeah we think we can get 20~30MHz timing from both SAMD51 and RP2040 hardware just bitbanging the GPIO and incrementing a counter. counts are about 25, 60, and 85 so there's a little leeway while allowing for longer pulses. eventually we may add capture peripheral support and/or PIO. it ought to be possible, we just haven't sat down to try it yet! we're happy to tell folks that the hardware is unofficial and that folks should try official hardware if they're having difficulties reading a particular diskette. if anybody opens an issue asking for help/support with Adafruit_Floppy built hardware, you can ask them to re-open it in the Adafruit_Floppy repo and i'll take care of it the best i can.
3. we've removed the debugging stuffs
4. im going to look into the USB strings detection method. since the USB code is generated from Arduino, we cant change serial number (its going to be chips internal unique ID), manufacturer, VID, or PID. but i do see a function to set the descriptor string, hopefully its accessible, and will update this PR when thats tested!

**Comment by ladyada** [comment]
@keirf ok theres no guaranteed way in arduino to change the USB descriptor strings and make sure pyserial sees them so going to VID/PID lock it for now! will revisit if we come up with something :) this can be reviewed again

**Comment by keirf** [comment]
1. Sounds fine to me. Will the hardware support more protocols than Greaseweazle then? (eg multiple firmwares)
2. The main issues with the software counter as-is are: unknown exact tick frequency (except by empirical inspection), and by counting from zero each time you potentially drop "ticks" while you're outside the tight poll loop. It would be a big improvement even if you could rely on a system timer register, ticking at a known rate, and read that on exit of the tight poll loop, and record the delta. Something like: `delta = current - prev; prev = current;`. No dropped ticks. Known frequency. Still not as good as a timer peripheral triggering on the input pin, but as good as it can get for GPIO.
3. Cool thanks
4. VID/PID is sufficient if it's for this hardware project specifically. So 239a:8002 is I suppose good as that's Adafruit VID and you will have chosen a fresh PID (and you must have some way of specifying it as it's not an MCU manufacturer or library default?) Whereas 2e8a:000a is generic Pi Pico. Can you not modify the Pico's advertised VID/PID?

**Comment by keirf** [comment]
Regarding serial, it doesn't really matter that much: I use it to find the same Greaseweazle when I reset the device into (or out of) firmware update mode. But you probably won't use my update mechanism, so there will be no mode switching, and keying off serial is not necessary.

**Comment by ladyada** [comment]
more replies :)

- yes! one nice thing about the bootloader is you can 'double click' to launch a bootloader disk drive, so folks can drag on different firmware. for example, one could turn it into a MIDI device so you can 'play sounds' on disk drives
- its a good idea, we'll almost certainly get there, as every capture peripheral is different. you can get away with a lot when a chip runs at 200MHz and has 256K of SRAM :)
- correct - you *cannot* change the VID/PID of arduino-programmed boards, it is fixed in the IDE, so these are arduino-defined PIDs. there *is* a way to get the USB descriptor strings in more detail, so that we could specify only these boards, programmed with this arduino sketch - but not in a cross platform way via pyserial! its' just not exposed to python - in windows for example, pyserial reports the manufacturer as Microsoft because the driver for windows 10 is the generic CDC one published by microsoft. we did find a way to do this cross platform and made it into a library https://github.com/adafruit/Adafruit_Board_Toolkit but it would add a dependency. if you're ok with the dependency i can add that so its not just vid/pid but i dug thru everything in the port structure and nothing was identifyable.

**Comment by keirf** [comment]
Ah yes I forgot Microsoft hides the real strings for COM devices. Greaseweazle is relying on VID:PID for Windows. But I'm not going to put any (more) non-specific VID:PID pairs into the tools. At the end of the day, users can still use the tools by explicitly naming the COM port (`--device COM3` or whatever). Indeed, that given, the tools probably work as is without any patching at all, albeit you won't get a nice informative name out of `gw info`. Regarding those names: your original vanilla/default name was fine, in fact better than the new one.

**Comment by ladyada** [comment]
oh i didnt realize that `--device` was available, its not in the help text, want me to add it there?

**Comment by keirf** [comment]
It's actually an argument to every gw subcommand and it is in their respective help texts (eg `gw read -h`). Possibly it should be pulled out into the wrapper script but it would mean more fighting with the argument parser. Also I may add subcommands in future which don't use a device.

The subcommand help text is not perfect. `gw read` ought to at least mention existence of `-h` I suppose!

**Comment by keirf** [comment]
Adafruit-board-library looks interesting. But is there a clean list_ports interface to it which doesn't filter on CircuitPython names?

**Comment by ladyada** [comment]
i think the thing is i saw 'device name' and didnt equate that with 'COM / Serial port' i could also add a short amount of text. or just document it (--device didnt appear in any documentation we saw either lol). so up to you if you want me to keep the VID/PID stuff or remove it.

we could add it, it was designed to solve this problem for circuitpython boards, but its under active development.

**Comment by keirf** [comment]
I won't take generic Arduino VID:PID pairs. The only other avenue there would be adafruit-board-library therefore I think.

Yes, "COM/serial port" is much better. I can fix that. Greaseweazle documentation is really bad I'm afraid, not least because it's missing a comprehensive command reference. That and some use-case walkthroughs are badly needed.

**Comment by keirf** [comment]
In terms of your patches, do you just want me to patch `gw info` for your model=8, submodel=0 for now? Or are device names still TBD?

**Comment by ladyada** [comment]
ok done! ill def document some use cases as im imaging some disks

is there a way to grab fluxes in like SCP format while *also* verifying format like MFM? e.g. grab flux, check the format is what you expect (18/18 MFM sectors) and then save in SCP? we couldnt figure out how to do it. if not, would you take a PR to do that? 
(store is i am able to read a disk MFM into img file just fine, but when i grab the SCP, hxc says some sectors are corrupt, not sure if its hxc or bad reads or what...so having sector checks could help)

**Comment by ladyada** [comment]
yes please keep this patch for the generic 8 0 naming, i can get more specific later!

**Comment by keirf** [comment]
Yes you can now `gw read --format=ibm.1440 a.img`. This is as of the latest tools release, so very new!

**Comment by ladyada** [comment]
ok awesome, thanks, i will try it! :) i think this PR is minimal and complete now

**Comment by keirf** [comment]
Ok manually applied the 8 0 naming. This PR is done. Anything else: new issue/pr.

**Comment by keirf** [comment]
Oh one thing to say on the verifying as dumping to raw: Currently the track gets decoded, verified, and *reconstructed*. So the dump is actually a perfect reconstruction of the track. Possibly that is not what is wanted, and a raw dump would be preferred.... At least I should probably give the option to tee a raw dump as well as the processed dump?

**Comment by keirf** [comment]
For example: `gw read --format=ibm.1440 a.scp`

a.scp will contain the dumped logical sector contents reframed into perfect tracks, as if `gw` were writing a disk from an IMG file. Currently no way for a.scp to contain the actual dumped imperfect raw flux, if `--format` is specified.

**Comment by ladyada** [comment]
hiya yah the second thing is what we mean: running `gw read --format=ibm.1440 a.scp` would mean the raw flux timing is saved, unprocessed, as SCP. and, during capture, we try to verify/decode the format so that we can retry a few times or warn folks that the data is not completely valid. maybe a new arg calld like `--check-format` or `--verify-format`

i can open a new issue and/or just do this as a PR -  just let me know ! :)

**Comment by ourIThome** [comment]
In kryoflux command line, you would do something like DTC.exe -f"c:\game\track" -i0 -i5

This tells KF to dump raw tracks (-i0), but verify as amigados(-i5).  I could add an additional -f for the adf file.

It will all start to get messy if you have a tri formatted disk Amiga / ST / PC.  I'm not sure if there is a possibility of reading flux in, auto verifying against a set of known disk layouts on each track.... Messy?

As the files are each track and side... Knowing you have a bad dump track and or side, is a simple delete said file, clean disk redump specific track and side.

I can see a case for a repair for scp type files, where tracks / sides are deleted and new rereads are merged into the scp file.

**Comment by keirf** [comment]
This is now supported via new `--raw` option to `gw read`. This will respect the `--format` for verification purposes, but all raw flux reads for the track (across retries) will be concatenated into the raw output file. Of course the output file must be a raw type (SCP, HFE, Kryoflux).

**Comment by ladyada** [comment]
incredible! ill try it out shortly.

**Pull request closed without merging**
